### ISSUE TITLE
Mod Dont Load

### ISSUE THREAD

**Issue by f0kx** [LegoMaster3650/Inventory-Crafter#1]
https://pastebin.com/jE9zHnnN

From ym Latest log because no crashlog

**Comment by LegoMaster3650** [comment]
Should be fixed in 1.0.1 (1.18.2)/1.1.1 (1.19.2), give curseforge about an hour to approve the updates

**Comment by genesy** [comment]
still doesn't load on  1.1.1

**Comment by genesy** [comment]
i see the mod on the modlist and the keybind but no button and the keybind action doesn't trigger anything

**Comment by LegoMaster3650** [comment]
@genesy Anything in your latest.log? (Or is it the same as in the posted log?)

**Comment by LegoMaster3650** [comment]
Also both of you: what game version? (1.18.2 or 1.19.2)

**Comment by genesy** [comment]
Can't give latest.log rn but I'm on 1.19.2

**Comment by LegoMaster3650** [comment]
alright, looking into it more. I did code this in like 4 hours with minimal testing...

**Comment by LegoMaster3650** [comment]
Wait do you have a crafting table in your inventory

**Comment by LegoMaster3650** [comment]
You need that for the button/keybind (for balance, its QOL not a magic step skipper, although maybe I should make *that* configurable)

**Comment by genesy** [comment]
Oh i only had crafting table from crafting on a stick maybe. I'll try it again later.

**Comment by LegoMaster3650** [comment]
Yeah there is a tag for if you really need that (`inventory_crafter:crafting_tables`) but I advise just a regular vanilla table item.

**Comment by LegoMaster3650** [comment]
Keeping this open because I want to hear from @SugarDaddii, does any update 1.x.1 or above work for you now?

**Comment by f0kx** [comment]
Iam at work right now … can test it again in the afternoon 😁

**Comment by f0kx** [comment]
![image](https://user-images.githubusercontent.com/14795020/220188114-74e76ac5-2b70-480d-a651-a65d9611bebf.png)
Its working yes

**Comment by f0kx** [comment]
iam on version 1.1.2 latest

**Comment by LegoMaster3650** [comment]
Alright, closing the issue. If your problem occurs even with a vanilla crafting table @genesy open a new issue as I believe it is likely unrelated.
