### ISSUE TITLE
Incompatible with Quark's Disable Recipe Book

### ISSUE THREAD

**Issue by ElMolgajete** [LegoMaster3650/Inventory-Crafter#5]
When I use this option the button just dissapears and in its place it is the Recipe Book button.
When I disabled the Quark Feature:
![2023-03-01_11 07 19](https://user-images.githubusercontent.com/122349451/222211486-1fb5faf5-1454-4a76-84e3-e4fc7a000967.png)
When I enable it:
![2023-03-01_11 07 41](https://user-images.githubusercontent.com/122349451/222211626-08b67729-c9eb-47ab-b864-8ff08520c820.png)

**Comment by LegoMaster3650** [comment]
Did some looking into it, and it seems quark kinda just disables all buttons with pictures in the player inventory with this tweak on! I will look into possible solutions, but this may prove a bit challenging...

**Comment by LegoMaster3650** [comment]
I think I'll report this on quark's end, asking for some form of recipe book only filter. For the time being, look for a mod that removes the recipe book specifically, as it would require unsafe tricks to fix this on my mod's side.

**Comment by LegoMaster3650** [comment]
Took one more look at this and realized only the "first" (internally ordered) image button is killed by quark, so I can fix this problem and will release a patch soon. I'll also add a preset to put the button where the recipe book previously sat in this patch because why not
